// قاموس ترجمة الكلمات الإنجليزية → العربية (للكلمات القابلة للنقر)
export const WORD_GLOSSARY: Record<string, string> = {
  "a cat": "قطة",
  "a rabbit": "أرنب",
  "a table": "طاولة",
  "airplane": "طائرة",
  "airport": "مطار",
  "aisle seat": "مقعد الممر",
  "always": "دائماً",
  "are": "تكون",
  "are you": "أنت",
  "arrival": "الوصول",
  "arrives": "يصل",
  "autumn": "خريف",
  "bank": "بنك",
  "before landing": "قبل الهبوط",
  "behind": "خلف",
  "between": "بين",
  "big": "كبير",
  "big dog": "كلب كبير",
  "bigger than": "أكبر من",
  "bird": "طائر",
  "bitter": "مرّ",
  "black": "أسود",
  "blue": "أزرق",
  "board": "الصعود",
  "boarding": "الصعود للطائرة",
  "boarding pass": "بطاقة الصعود",
  "boards": "يصعد",
  "bread": "خبز",
  "breakfast": "فطور",
  "brother": "أخ",
  "build": "يبني",
  "but not": "لكن ليس",
  "cafe": "مقهى",
  "cake": "كيك",
  "care": "عناية",
  "care for": "ترغب",
  "cat": "قطة",
  "chicken": "دجاج",
  "chicken soup": "شوربة دجاج",
  "city": "مدينة",
  "cloudy": "غائم",
  "coffee": "قهوة",
  "coffee please": "قهوة من فضلك",
  "cold": "بارد",
  "come": "يأتي",
  "come home": "يعود للبيت",
  "cook": "يطبخ",
  "country": "بلد",
  "cup": "كوب",
  "cute": "لطيف",
  "daughter": "بنت",
  "day": "يوم",
  "delay": "تأخير",
  "delicious": "لذيذ",
  "depart": "يغادر",
  "departs": "يغادر",
  "departure": "المغادرة",
  "dessert": "حلوى",
  "doctor": "طبيب",
  "dog": "كلب",
  "drink": "مشروب",
  "drive": "يقود",
  "driver": "سائق",
  "early": "مبكراً",
  "eat": "يأكل",
  "enough": "يكفي",
  "evening": "مساء",
  "every day": "كل يوم",
  "excuse me": "عذراً",
  "family": "عائلة",
  "far": "بعيد",
  "fast": "سريع",
  "faster than": "أسرع من",
  "father": "أب",
  "favourite drink": "المشروب المفضل",
  "feed": "يُطعم",
  "fish": "سمكة",
  "flight": "رحلة جوية",
  "fluffy": "كثيف الفرو",
  "food": "طعام",
  "fresh": "طازج",
  "fresh salad": "سلطة طازجة",
  "friday": "الجمعة",
  "friend": "صديق",
  "friendly": "ودود",
  "from": "من",
  "gate": "بوابة",
  "generosity": "السخاء",
  "gentle": "وديع",
  "glass": "كأس",
  "go": "يذهب",
  "go straight": "اذهب مستقيماً",
  "good morning": "صباح الخير",
  "good night": "تصبح على خير",
  "goodbye": "مع السلامة",
  "grandfather": "جد",
  "green": "أخضر",
  "groom": "يعتني",
  "have": "أملك",
  "he builds": "هو يبني",
  "he cooks": "هو يطبخ",
  "he teaches": "هو يُعلّم",
  "he writes": "هو يكتب",
  "hello": "مرحباً",
  "here": "هنا",
  "hi": "أهلاً",
  "home": "بيت",
  "hospital": "مستشفى",
  "hospitality": "الكرم",
  "hot": "حار",
  "hot coffee": "قهوة ساخنة",
  "hot soup": "شوربة ساخنة",
  "how": "كيف",
  "i am": "أنا",
  "i cook": "أنا أطبخ",
  "i drive": "أنا أقود",
  "i eat": "أنا آكل",
  "i feed": "أُطعم",
  "i go": "أنا أذهب",
  "i have": "أملك",
  "i read": "أنا أقرأ",
  "i sleep": "أنا أنام",
  "i teach": "أنا أُعلّم",
  "i walk": "أنا أمشي",
  "i want": "أريد",
  "i work": "أنا أعمل",
  "i write": "أنا أكتب",
  "i'd like": "أودّ",
  "ice cream": "آيس كريم",
  "in autumn": "في الخريف",
  "in summer": "في الصيف",
  "in winter": "في الشتاء",
  "instead": "بدلاً عنه",
  "is she": "هي",
  "it's hot": "الجو حار",
  "job": "وظيفة",
  "juice": "عصير",
  "landing": "الهبوط",
  "left": "يسار",
  "like": "أحب",
  "looks": "يبدو",
  "looks old": "يبدو قديماً",
  "looks tall": "يبدو عالياً",
  "luggage": "أمتعة",
  "market": "سوق",
  "meal": "وجبة",
  "meet you": "ألقاك",
  "menu": "قائمة الطعام",
  "milk": "حليب",
  "monday": "الإثنين",
  "more": "المزيد",
  "morning": "صباح",
  "mother": "أم",
  "my dog": "كلبي",
  "my family": "عائلتي",
  "my father": "أبي",
  "my flight": "رحلتي",
  "my luggage": "أمتعتي",
  "my mother": "أمي",
  "my name": "اسمي",
  "my passport": "جوازي",
  "my sister": "أختي",
  "name": "اسم",
  "near": "قريب",
  "near here": "قريب من هنا",
  "never": "أبداً",
  "new": "جديد",
  "next to": "بجانب",
  "nice": "جميل",
  "night": "ليل",
  "no": "لا",
  "now boarding": "الصعود الآن",
  "often": "غالباً",
  "old": "قديم",
  "older than": "أقدم من",
  "order": "يطلب",
  "park": "حديقة",
  "passport": "جواز سفر",
  "pet": "حيوان أليف",
  "play": "يلعب",
  "play football": "يلعب كرة القدم",
  "play with": "يلعب مع",
  "playful": "مرح",
  "please": "من فضلك",
  "prefer": "تفضّل",
  "rabbit": "أرنب",
  "rainy": "ممطر",
  "read": "يقرأ",
  "rice": "أرز",
  "right": "يمين",
  "salad": "سلطة",
  "school": "مدرسة",
  "season": "فصل",
  "seat": "مقعد",
  "seat belt": "حزام الأمان",
  "she drives": "هي تقود",
  "she teaches": "هي تُعلّم",
  "she works": "هي تعمل",
  "she writes": "هي تكتب",
  "short": "قصير",
  "sister": "أخت",
  "sleep": "ينام",
  "sleep early": "ينام مبكراً",
  "slow": "بطيء",
  "small": "صغير",
  "small cat": "قطة صغيرة",
  "smaller than": "أصغر من",
  "snowy": "مثلج",
  "so": "جداً",
  "so hot": "حار جداً",
  "so tall": "عالٍ جداً",
  "some": "بعض",
  "some cake": "بعض الكيك",
  "some juice": "بعض العصير",
  "some more": "مزيد",
  "some soup": "بعض الشوربة",
  "sometimes": "أحياناً",
  "son": "ابن",
  "sorry": "آسف",
  "soup": "شوربة",
  "spring": "ربيع",
  "stop": "توقّف",
  "sugar": "سكر",
  "summer": "صيف",
  "sunday": "الأحد",
  "sunny": "مشمس",
  "sweet": "حلو",
  "table": "طاولة",
  "tall": "طويل",
  "tea": "شاي",
  "tea please": "شاي من فضلك",
  "teach": "يُعلّم ‍",
  "teacher": "معلّم",
  "than": "من",
  "thank you": "شكراً",
  "the biggest": "الأكبر",
  "the bill": "الفاتورة",
  "the fastest": "الأسرع",
  "the hospital": "المستشفى",
  "the menu": "القائمة",
  "the most": "الأكثر",
  "the oldest": "الأقدم",
  "the summer": "الصيف",
  "the vet": "الطبيب البيطري",
  "the weather": "الطقس",
  "there": "هناك",
  "they build": "هم يبنون",
  "they cook": "هم يطبخون",
  "they work": "هم يعملون",
  "this is": "هذا",
  "ticket": "تذكرة",
  "time": "وقت",
  "to order": "أن أطلب",
  "today": "اليوم",
  "travel": "سفر",
  "trouble": "إزعاج",
  "turn left": "انعطف يساراً",
  "turn right": "انعطف يميناً",
  "two brothers": "أخوان",
  "usually": "عادةً",
  "very": "جداً",
  "very cold": "بارد جداً",
  "very fast": "سريع جداً",
  "very old": "قديم جداً",
  "very playful": "مرح جداً",
  "very sorry": "آسف جداً",
  "very sweet": "حلو جداً",
  "very tall": "عالٍ جداً",
  "very windy": "عاصف جداً",
  "vet": "طبيب بيطري",
  "waiter": "نادل",
  "wake up": "يستيقظ",
  "walk": "يمشي",
  "want": "أريد",
  "warm": "دافئ",
  "warm milk": "حليب دافئ",
  "was wonderful": "ماضي",
  "watch": "يشاهد",
  "watch tv": "يشاهد التلفاز",
  "water": "ماء",
  "weather": "طقس",
  "week": "أسبوع",
  "welcome": "عفواً",
  "what": "ما",
  "what is": "ما هو",
  "where": "أين",
  "white": "أبيض",
  "window seat": "مقعد النافذة",
  "windy": "عاصف",
  "winter": "شتاء",
  "with": "مع",
  "with us": "معنا",
  "without": "بدون",
  "without sugar": "بدون سكر",
  "work": "عمل",
  "would": "سأودّ",
  "would like": "أود",
  "write": "يكتب",
  "write stories": "أكتب قصصاً",
  "yellow": "أصفر",
  "yes": "نعم",
  "yes please": "نعم من فضلك",
  "you": "أنت",
  "your": "خاصتك",
  "your job": "وظيفتك",
  "your name": "اسمك",

  // ═══════ القسم الثاني — مفردات أساسية ═══════
  // ملابس
  "shirt": "قميص", "dress": "فستان", "shoes": "حذاء", "jacket": "سترة",
  "sweater": "كنزة", "jeans": "جينز", "scarf": "وشاح", "gloves": "قفازات",
  "boots": "حذاء طويل", "hat": "قبعة", "socks": "جوارب", "coat": "معطف",
  "size": "مقاس", "color": "لون", "wear": "يرتدي", "fit": "يناسب",
  "tight": "ضيّق", "loose": "واسع", "wool": "صوف", "cotton": "قطن",
  // منزل
  "house": "منزل", "room": "غرفة", "kitchen": "مطبخ", "bedroom": "غرفة نوم",
  "bathroom": "حمّام", "living room": "غرفة المعيشة", "door": "باب", "window": "نافذة",
  "table": "طاولة", "chair": "كرسي", "bed": "سرير", "sofa": "أريكة",
  "wall": "جدار", "floor": "أرضية", "garden": "حديقة", "garage": "كراج",
  // فعل to be
  "am": "أكون", "is": "يكون", "are": "يكونون", "be": "يكون",
  "isn't": "ليس", "aren't": "ليسوا", "i'm": "أنا", "you're": "أنت",
  "he's": "هو", "she's": "هي", "it's": "إنه", "we're": "نحن", "they're": "هم",
  // المطعم
  "menu": "قائمة طعام", "order": "يطلب", "waiter": "نادل", "bill": "فاتورة",
  "meal": "وجبة", "appetizer": "مقبّلات", "dessert": "حلوى", "drink": "مشروب",
  "delicious": "لذيذ", "fork": "شوكة", "knife": "سكين", "spoon": "ملعقة",
  "plate": "طبق", "glass": "كوب", "napkin": "منديل",
  // العمل
  "office": "مكتب", "meeting": "اجتماع", "email": "بريد إلكتروني", "boss": "مدير",
  "colleague": "زميل", "client": "عميل", "report": "تقرير", "project": "مشروع",
  "deadline": "موعد نهائي", "task": "مهمة", "plan": "خطة", "employee": "موظف",
  // المشاعر
  "happy": "سعيد", "sad": "حزين", "angry": "غاضب", "tired": "متعب",
  "scared": "خائف", "excited": "متحمس", "bored": "ملول", "worried": "قلق",
  "calm": "هادئ", "nervous": "متوتر", "proud": "فخور", "feel": "يشعر",
  "because": "لأن", "when": "عندما", "makes": "يجعل",
  // الصف
  "teacher": "معلّم", "student": "طالب", "question": "سؤال", "answer": "إجابة",
  "book": "كتاب", "pen": "قلم", "paper": "ورقة", "lesson": "درس",
  "understand": "يفهم", "repeat": "يكرّر", "explain": "يشرح", "spell": "يتهجّى",
  // الوقت
  "time": "وقت", "hour": "ساعة", "minute": "دقيقة", "clock": "ساعة حائط",
  "morning": "صباح", "afternoon": "بعد الظهر", "evening": "مساء", "night": "ليل",
  "today": "اليوم", "tomorrow": "غداً", "yesterday": "أمس", "now": "الآن",
  "noon": "ظهر", "midnight": "منتصف الليل", "early": "مبكّر", "late": "متأخّر",
  // الرياضة
  "football": "كرة قدم", "basketball": "كرة سلة", "tennis": "تنس", "swimming": "سباحة",
  "running": "جري", "team": "فريق", "match": "مباراة", "game": "لعبة",
  "player": "لاعب", "coach": "مدرّب", "goal": "هدف", "win": "يفوز", "lose": "يخسر",
  "score": "نتيجة", "favorite": "مفضّل",
  // ظروف التكرار
  "always": "دائماً", "usually": "عادةً", "sometimes": "أحياناً", "never": "أبداً",
  "often": "غالباً", "rarely": "نادراً", "every": "كل", "once": "مرة", "twice": "مرتين",
  // الروتين
  "wake up": "يستيقظ", "breakfast": "فطور", "lunch": "غداء", "dinner": "عشاء",
  "shower": "دش", "work": "عمل", "sleep": "ينام", "first": "أولاً",
  "then": "ثم", "after": "بعد", "finally": "أخيراً", "relax": "يسترخي",
  // الفندق
  "hotel": "فندق", "reception": "استقبال", "key": "مفتاح", "booking": "حجز",
  "guest": "نزيل", "single": "فردي", "double": "مزدوج", "available": "متاح",
  "reserve": "يحجز", "luggage": "أمتعة", "check in": "تسجيل وصول", "check out": "تسجيل مغادرة",
  // أدوات التعريف
  "the": "الـ (التعريف)", "an": "أداة نكرة",
  // العائلة
  "father": "أب", "mother": "أم", "brother": "أخ", "sister": "أخت",
  "grandfather": "جدّ", "grandmother": "جدّة", "uncle": "عمّ/خال", "aunt": "عمّة/خالة",
  "cousin": "ابن العم", "parents": "والدان", "family": "عائلة", "son": "ابن", "daughter": "ابنة",
  "kind": "لطيف", "funny": "مضحك", "smart": "ذكي", "friendly": "ودود",
  // الملكية
  "my": "خاصتي", "his": "خاصته", "her": "خاصتها", "our": "خاصتنا", "their": "خاصتهم",
  "mine": "ملكي", "yours": "ملكك", "whose": "لمن", "phone": "هاتف",
  "watch": "ساعة يد", "bag": "حقيبة", "keys": "مفاتيح", "wallet": "محفظة",
  "glasses": "نظارة", "umbrella": "مظلّة", "laptop": "حاسوب محمول",
  // المفقودات
  "lost": "مفقود", "found": "وُجد", "missing": "ناقص", "describe": "يصف",
  "shape": "شكل", "leather": "جلد", "plastic": "بلاستيك", "metal": "معدن",
  // الجموع
  "men": "رجال", "women": "نساء", "children": "أطفال", "feet": "أقدام",
  "teeth": "أسنان", "people": "أشخاص", "mice": "فئران",
  "these": "هؤلاء", "those": "أولئك", "many": "كثير",
  // المدينة
  "bank": "بنك", "station": "محطة", "square": "ساحة", "corner": "زاوية",
  "bridge": "جسر", "street": "شارع", "left": "يسار", "right": "يمين",
  "straight": "مستقيم", "far": "بعيد", "near": "قريب", "map": "خريطة",
  // النفي
  "don't": "لا (نفي)", "doesn't": "لا (نفي)", "not": "ليس",
  // الأعراض
  "head": "رأس", "stomach": "معدة", "throat": "حلق", "pain": "ألم",
  "fever": "حُمّى", "cough": "سعال", "cold": "زكام", "sick": "مريض",
  "medicine": "دواء", "rest": "راحة", "doctor": "طبيب", "headache": "صداع",
  "hurts": "يؤلم", "dizzy": "دائخ",
  // المضارع المستمر
  "reading": "يقرأ", "playing": "يلعب", "eating": "يأكل", "working": "يعمل",
  "watching": "يشاهد", "writing": "يكتب", "cooking": "يطبخ", "sleeping": "ينام",
  "doing": "يفعل", "going": "يذهب", "currently": "حالياً",
  // الطقس والطبيعة
  "sunny": "مشمس", "rainy": "ممطر", "cloudy": "غائم", "windy": "عاصف",
  "snowy": "مثلج", "hot": "حارّ", "warm": "دافئ", "cool": "منعش",
  "weather": "طقس", "season": "فصل", "summer": "صيف", "winter": "شتاء",
  "spring": "ربيع", "autumn": "خريف", "mountain": "جبل", "river": "نهر",
  "forest": "غابة", "beach": "شاطئ", "lake": "بحيرة", "sea": "بحر", "nature": "طبيعة",
  // المدرسة
  "math": "رياضيات", "science": "علوم", "history": "تاريخ", "art": "فنون",
  "music": "موسيقى", "homework": "واجب", "exam": "امتحان", "grade": "درجة",
  "classroom": "صف", "library": "مكتبة", "subject": "مادة", "study": "يدرس",
  "learn": "يتعلّم", "geography": "جغرافيا", "chemistry": "كيمياء", "biology": "أحياء",
  // أفعال الأمر
  "sit": "اجلس", "stand": "قف", "open": "افتح", "close": "أغلق",
  "listen": "استمع", "look": "انظر", "come": "تعال", "wait": "انتظر",
  "press": "اضغط", "put": "ضع", "take": "خذ", "follow": "اتبع",
  "please": "من فضلك", "pull": "اسحب", "push": "ادفع",
  // السلامة
  "danger": "خطر", "warning": "تحذير", "careful": "حذِر", "stop": "قف",
  "safe": "آمن", "must": "يجب", "emergency": "طوارئ", "fire": "حريق",
  "help": "مساعدة", "police": "شرطة", "ambulance": "إسعاف", "exit": "مخرج",
};

export function translateWord(word: string): string | null {
  const key = word.toLowerCase().replace(/[.,!?]/g, "").trim();
  return WORD_GLOSSARY[key] ?? null;
}