// قاموس ترجمة الكلمات الإنجليزية → العربية (للكلمات القابلة للنقر)
export const WORD_GLOSSARY: Record<string, string> = {
  "a cat": "قطة",
  "a rabbit": "أرنب",
  "a table": "طاولة",
  "airplane": "طائرة",
  "airport": "مطار",
  "aisle seat": "مقعد الممر",
  "always": "دائماً",
  "are": "تكون",
  "are you": "أنت",
  "arrival": "الوصول",
  "arrives": "يصل",
  "autumn": "خريف",
  "bank": "بنك",
  "before landing": "قبل الهبوط",
  "behind": "خلف",
  "between": "بين",
  "big": "كبير",
  "big dog": "كلب كبير",
  "bigger than": "أكبر من",
  "bird": "طائر",
  "bitter": "مرّ",
  "black": "أسود",
  "blue": "أزرق",
  "board": "الصعود",
  "boarding": "الصعود للطائرة",
  "boarding pass": "بطاقة الصعود",
  "boards": "يصعد",
  "bread": "خبز",
  "breakfast": "فطور",
  "brother": "أخ",
  "build": "يبني",
  "but not": "لكن ليس",
  "cafe": "مقهى",
  "cake": "كيك",
  "care": "عناية",
  "care for": "ترغب",
  "cat": "قطة",
  "chicken": "دجاج",
  "chicken soup": "شوربة دجاج",
  "city": "مدينة",
  "cloudy": "غائم",
  "coffee": "قهوة",
  "coffee please": "قهوة من فضلك",
  "cold": "بارد",
  "come": "يأتي",
  "come home": "يعود للبيت",
  "cook": "يطبخ",
  "country": "بلد",
  "cup": "كوب",
  "cute": "لطيف",
  "daughter": "بنت",
  "day": "يوم",
  "delay": "تأخير",
  "delicious": "لذيذ",
  "depart": "يغادر",
  "departs": "يغادر",
  "departure": "المغادرة",
  "dessert": "حلوى",
  "doctor": "طبيب",
  "dog": "كلب",
  "drink": "مشروب",
  "drive": "يقود",
  "driver": "سائق",
  "early": "مبكراً",
  "eat": "يأكل",
  "enough": "يكفي",
  "evening": "مساء",
  "every day": "كل يوم",
  "excuse me": "عذراً",
  "family": "عائلة",
  "far": "بعيد",
  "fast": "سريع",
  "faster than": "أسرع من",
  "father": "أب",
  "favourite drink": "المشروب المفضل",
  "feed": "يُطعم",
  "fish": "سمكة",
  "flight": "رحلة جوية",
  "fluffy": "كثيف الفرو",
  "food": "طعام",
  "fresh": "طازج",
  "fresh salad": "سلطة طازجة",
  "friday": "الجمعة",
  "friend": "صديق",
  "friendly": "ودود",
  "from": "من",
  "gate": "بوابة",
  "generosity": "السخاء",
  "gentle": "وديع",
  "glass": "كأس",
  "go": "يذهب",
  "go straight": "اذهب مستقيماً",
  "good morning": "صباح الخير",
  "good night": "تصبح على خير",
  "goodbye": "مع السلامة",
  "grandfather": "جد",
  "green": "أخضر",
  "groom": "يعتني",
  "have": "أملك",
  "he builds": "هو يبني",
  "he cooks": "هو يطبخ",
  "he teaches": "هو يُعلّم",
  "he writes": "هو يكتب",
  "hello": "مرحباً",
  "here": "هنا",
  "hi": "أهلاً",
  "home": "بيت",
  "hospital": "مستشفى",
  "hospitality": "الكرم",
  "hot": "حار",
  "hot coffee": "قهوة ساخنة",
  "hot soup": "شوربة ساخنة",
  "how": "كيف",
  "i am": "أنا",
  "i cook": "أنا أطبخ",
  "i drive": "أنا أقود",
  "i eat": "أنا آكل",
  "i feed": "أُطعم",
  "i go": "أنا أذهب",
  "i have": "أملك",
  "i read": "أنا أقرأ",
  "i sleep": "أنا أنام",
  "i teach": "أنا أُعلّم",
  "i walk": "أنا أمشي",
  "i want": "أريد",
  "i work": "أنا أعمل",
  "i write": "أنا أكتب",
  "i'd like": "أودّ",
  "ice cream": "آيس كريم",
  "in autumn": "في الخريف",
  "in summer": "في الصيف",
  "in winter": "في الشتاء",
  "instead": "بدلاً عنه",
  "is she": "هي",
  "it's hot": "الجو حار",
  "job": "وظيفة",
  "juice": "عصير",
  "landing": "الهبوط",
  "left": "يسار",
  "like": "أحب",
  "looks": "يبدو",
  "looks old": "يبدو قديماً",
  "looks tall": "يبدو عالياً",
  "luggage": "أمتعة",
  "market": "سوق",
  "meal": "وجبة",
  "meet you": "ألقاك",
  "menu": "قائمة الطعام",
  "milk": "حليب",
  "monday": "الإثنين",
  "more": "المزيد",
  "morning": "صباح",
  "mother": "أم",
  "my dog": "كلبي",
  "my family": "عائلتي",
  "my father": "أبي",
  "my flight": "رحلتي",
  "my luggage": "أمتعتي",
  "my mother": "أمي",
  "my name": "اسمي",
  "my passport": "جوازي",
  "my sister": "أختي",
  "name": "اسم",
  "near": "قريب",
  "near here": "قريب من هنا",
  "never": "أبداً",
  "new": "جديد",
  "next to": "بجانب",
  "nice": "جميل",
  "night": "ليل",
  "no": "لا",
  "now boarding": "الصعود الآن",
  "often": "غالباً",
  "old": "قديم",
  "older than": "أقدم من",
  "order": "يطلب",
  "park": "حديقة",
  "passport": "جواز سفر",
  "pet": "حيوان أليف",
  "play": "يلعب",
  "play football": "يلعب كرة القدم",
  "play with": "يلعب مع",
  "playful": "مرح",
  "please": "من فضلك",
  "prefer": "تفضّل",
  "rabbit": "أرنب",
  "rainy": "ممطر",
  "read": "يقرأ",
  "rice": "أرز",
  "right": "يمين",
  "salad": "سلطة",
  "school": "مدرسة",
  "season": "فصل",
  "seat": "مقعد",
  "seat belt": "حزام الأمان",
  "she drives": "هي تقود",
  "she teaches": "هي تُعلّم",
  "she works": "هي تعمل",
  "she writes": "هي تكتب",
  "short": "قصير",
  "sister": "أخت",
  "sleep": "ينام",
  "sleep early": "ينام مبكراً",
  "slow": "بطيء",
  "small": "صغير",
  "small cat": "قطة صغيرة",
  "smaller than": "أصغر من",
  "snowy": "مثلج",
  "so": "جداً",
  "so hot": "حار جداً",
  "so tall": "عالٍ جداً",
  "some": "بعض",
  "some cake": "بعض الكيك",
  "some juice": "بعض العصير",
  "some more": "مزيد",
  "some soup": "بعض الشوربة",
  "sometimes": "أحياناً",
  "son": "ابن",
  "sorry": "آسف",
  "soup": "شوربة",
  "spring": "ربيع",
  "stop": "توقّف",
  "sugar": "سكر",
  "summer": "صيف",
  "sunday": "الأحد",
  "sunny": "مشمس",
  "sweet": "حلو",
  "table": "طاولة",
  "tall": "طويل",
  "tea": "شاي",
  "tea please": "شاي من فضلك",
  "teach": "يُعلّم ‍",
  "teacher": "معلّم",
  "than": "من",
  "thank you": "شكراً",
  "the biggest": "الأكبر",
  "the bill": "الفاتورة",
  "the fastest": "الأسرع",
  "the hospital": "المستشفى",
  "the menu": "القائمة",
  "the most": "الأكثر",
  "the oldest": "الأقدم",
  "the summer": "الصيف",
  "the vet": "الطبيب البيطري",
  "the weather": "الطقس",
  "there": "هناك",
  "they build": "هم يبنون",
  "they cook": "هم يطبخون",
  "they work": "هم يعملون",
  "this is": "هذا",
  "ticket": "تذكرة",
  "time": "وقت",
  "to order": "أن أطلب",
  "today": "اليوم",
  "travel": "سفر",
  "trouble": "إزعاج",
  "turn left": "انعطف يساراً",
  "turn right": "انعطف يميناً",
  "two brothers": "أخوان",
  "usually": "عادةً",
  "very": "جداً",
  "very cold": "بارد جداً",
  "very fast": "سريع جداً",
  "very old": "قديم جداً",
  "very playful": "مرح جداً",
  "very sorry": "آسف جداً",
  "very sweet": "حلو جداً",
  "very tall": "عالٍ جداً",
  "very windy": "عاصف جداً",
  "vet": "طبيب بيطري",
  "waiter": "نادل",
  "wake up": "يستيقظ",
  "walk": "يمشي",
  "want": "أريد",
  "warm": "دافئ",
  "warm milk": "حليب دافئ",
  "was wonderful": "ماضي",
  "watch": "يشاهد",
  "watch tv": "يشاهد التلفاز",
  "water": "ماء",
  "weather": "طقس",
  "week": "أسبوع",
  "welcome": "عفواً",
  "what": "ما",
  "what is": "ما هو",
  "where": "أين",
  "white": "أبيض",
  "window seat": "مقعد النافذة",
  "windy": "عاصف",
  "winter": "شتاء",
  "with": "مع",
  "with us": "معنا",
  "without": "بدون",
  "without sugar": "بدون سكر",
  "work": "عمل",
  "would": "سأودّ",
  "would like": "أود",
  "write": "يكتب",
  "write stories": "أكتب قصصاً",
  "yellow": "أصفر",
  "yes": "نعم",
  "yes please": "نعم من فضلك",
  "you": "أنت",
  "your": "خاصتك",
  "your job": "وظيفتك",
  "your name": "اسمك",
};

export function translateWord(word: string): string | null {
  const key = word.toLowerCase().replace(/[.,!?]/g, "").trim();
  return WORD_GLOSSARY[key] ?? null;
}