import type { TieredBank } from "./types";

// ══════════════════════════════════════════════════════════════
// C1 – ADVANCED
// (Authored by content pass — see types.ts for the authoring rules.)
// ══════════════════════════════════════════════════════════════

export const c1Banks: Record<string, TieredBank> = {
  // ── Advanced Modal Verbs ──
  // Objective: precise uses of must/should/may/might/can/could/would,
  // past modals (should have / could have / might have), expressing
  // probability, expectation and necessity, persuasion & hedging.
  "Advanced Modal Verbs": {
    // EASY — recognition of core modal meanings, short sentences
    t0: [
      { id:"advmodal-t0-1", type:"word_order", sentence:"You must wear a helmet", correctAnswer:"You must wear a helmet", explanation:"must تُستخدم للإلزام والضرورة القوية", xp:10 },
      { id:"advmodal-t0-2", type:"translate", arabic:"ربما تمطر اليوم", options:["It may rain today","It must rain today","It can rain today","It would rain today"], correctAnswer:"It may rain today", explanation:"may تُستخدم للاحتمال الممكن", xp:10 },
      { id:"advmodal-t0-3", type:"listen_select", listenSentence:"You should drink more water", options:["should","must","could","would"], correctAnswer:"should", explanation:"الجملة: «يجدر بك شرب ماء أكثر» — should للنصيحة", xp:10 },
      { id:"advmodal-t0-4", type:"picture_match", word:"rain", pictureOptions:[{emoji:"🌧️",label:"rain"},{emoji:"☀️",label:"sun"},{emoji:"❄️",label:"snow"},{emoji:"🌈",label:"rainbow"}], correctAnswer:"rain", explanation:"It might rain 🌧️ — might للتنبؤ بالاحتمال", xp:10 },
      { id:"advmodal-t0-5", type:"word_order", sentence:"She can speak three languages", correctAnswer:"She can speak three languages", explanation:"can للتعبير عن القدرة", xp:11 },
      { id:"advmodal-t0-6", type:"translate", arabic:"يجدر بك زيارة الطبيب", options:["You should see a doctor","You may see a doctor","You can see a doctor","You would see a doctor"], correctAnswer:"You should see a doctor", explanation:"should للنصيحة والتوصية", xp:11 },
      { id:"advmodal-t0-7", type:"translate", arabic:"قد أتأخر قليلاً", options:["I might be a little late","I must be a little late","I can be a little late","I would be a little late"], correctAnswer:"I might be a little late", explanation:"might احتمال أضعف من may", xp:11 },
      { id:"advmodal-t0-8", type:"word_order", sentence:"Could you help me please", correctAnswer:"Could you help me please", explanation:"could للطلب المؤدب", xp:11 },
      { id:"advmodal-t0-9", type:"listen_select", listenSentence:"I can swim very well", options:["can","must","should","might"], correctAnswer:"can", explanation:"الجملة: «أستطيع السباحة جيداً» — can للقدرة", xp:11 },
      { id:"advmodal-t0-10", type:"picture_match", word:"doctor", pictureOptions:[{emoji:"🩺",label:"doctor"},{emoji:"👨‍🏫",label:"teacher"},{emoji:"👮",label:"police"},{emoji:"👨‍🍳",label:"chef"}], correctAnswer:"doctor", explanation:"You should see a doctor 🩺 = طبيب", xp:12 },
    ],
    // MEDIUM — distinguishing modals, negation, questions
    t1: [
      { id:"advmodal-t1-1", type:"translate", arabic:"لا يجوز لك التدخين هنا", options:["You mustn't smoke here","You shouldn't smoke here","You couldn't smoke here","You wouldn't smoke here"], correctAnswer:"You mustn't smoke here", explanation:"mustn't = المنع القاطع", xp:13 },
      { id:"advmodal-t1-2", type:"word_order", sentence:"You might want to check again", correctAnswer:"You might want to check again", explanation:"might want to — اقتراح لطيف غير مباشر", xp:13 },
      { id:"advmodal-t1-3", type:"translate", arabic:"لست مضطراً للقدوم مبكراً", options:["You don't have to come early","You mustn't come early","You shouldn't come early","You can't come early"], correctAnswer:"You don't have to come early", explanation:"don't have to = عدم الإلزام، وتختلف عن mustn't (المنع)", xp:14 },
      { id:"advmodal-t1-4", type:"listen_select", listenSentence:"He must be very tired now", options:["must","might","should","could"], correctAnswer:"must", explanation:"الجملة: «لا بد أنه متعب جداً» — must للاستنتاج المنطقي القوي", xp:14 },
      { id:"advmodal-t1-5", type:"word_order", sentence:"Would you mind closing the window", correctAnswer:"Would you mind closing the window", explanation:"Would you mind + v-ing — طلب مؤدب جداً", xp:13 },
      { id:"advmodal-t1-6", type:"translate", arabic:"قد لا يوافق المدير", options:["The manager may not agree","The manager mustn't agree","The manager can't not agree","The manager shouldn't agree"], correctAnswer:"The manager may not agree", explanation:"may not للتعبير عن احتمال عدم الحدوث", xp:14 },
      { id:"advmodal-t1-7", type:"word_order", sentence:"You ought to apologize to her", correctAnswer:"You ought to apologize to her", explanation:"ought to تكافئ should في معنى النصيحة", xp:14 },
      { id:"advmodal-t1-8", type:"picture_match", word:"phone", pictureOptions:[{emoji:"📱",label:"phone"},{emoji:"💻",label:"laptop"},{emoji:"📺",label:"television"},{emoji:"📷",label:"camera"}], correctAnswer:"phone", explanation:"Could you turn off your phone 📱 = هاتف", xp:13 },
      { id:"advmodal-t1-9", type:"translate", arabic:"هل لي أن أستخدم هاتفك؟", options:["May I use your phone?","Must I use your phone?","Would I use your phone?","Should I use your phone?"], correctAnswer:"May I use your phone?", explanation:"May I...? طلب الإذن بأسلوب رسمي", xp:15 },
      { id:"advmodal-t1-10", type:"listen_select", listenSentence:"You needn't worry about it", options:["needn't","mustn't","couldn't","wouldn't"], correctAnswer:"needn't", explanation:"الجملة: «لا داعي لأن تقلق» — needn't = لا حاجة", xp:15 },
    ],
    // HARD — past modals, deduction, nuance, trap distractors
    t2: [
      { id:"advmodal-t2-1", type:"translate", arabic:"كان يجب أن تتصل بي البارحة", options:["You should have called me yesterday","You must have called me yesterday","You should called me yesterday","You should have call me yesterday"], correctAnswer:"You should have called me yesterday", explanation:"should have + p.p للندم أو اللوم على الماضي", xp:16 },
      { id:"advmodal-t2-2", type:"word_order", sentence:"They must have missed the train", correctAnswer:"They must have missed the train", explanation:"must have + p.p للاستنتاج المؤكد عن الماضي", xp:16 },
      { id:"advmodal-t2-3", type:"translate", arabic:"ربما يكون قد نسي الاجتماع", options:["He might have forgotten the meeting","He might forgotten the meeting","He might have forget the meeting","He may forgotten the meeting"], correctAnswer:"He might have forgotten the meeting", explanation:"might have + p.p لاحتمال حدث في الماضي", xp:17 },
      { id:"advmodal-t2-4", type:"listen_select", listenSentence:"She could have won the race", options:["could","should","must","would"], correctAnswer:"could", explanation:"الجملة: «كان بإمكانها الفوز» — could have = كان ممكناً ولم يحدث", xp:17 },
      { id:"advmodal-t2-5", type:"word_order", sentence:"You needn't have paid so much", correctAnswer:"You needn't have paid so much", explanation:"needn't have + p.p — لم يكن ثمة داعٍ لما فعلتَه فعلاً", xp:18 },
      { id:"advmodal-t2-6", type:"translate", arabic:"لا بد أنها غادرت بالفعل", options:["She must have already left","She must already left","She must have already leave","She might already left"], correctAnswer:"She must have already left", explanation:"must have + already + p.p للاستنتاج القاطع", xp:17 },
      { id:"advmodal-t2-7", type:"word_order", sentence:"I would rather stay at home tonight", correctAnswer:"I would rather stay at home tonight", explanation:"would rather + مصدر مجرد للتفضيل", xp:16 },
      { id:"advmodal-t2-8", type:"picture_match", word:"train", pictureOptions:[{emoji:"🚆",label:"train"},{emoji:"🚌",label:"bus"},{emoji:"✈️",label:"plane"},{emoji:"🚕",label:"taxi"}], correctAnswer:"train", explanation:"They must have missed the train 🚆 = قطار", xp:16 },
      { id:"advmodal-t2-9", type:"translate", arabic:"ما كان ينبغي لك أن تقول ذلك", options:["You shouldn't have said that","You shouldn't said that","You mustn't have said that","You shouldn't have say that"], correctAnswer:"You shouldn't have said that", explanation:"shouldn't have + p.p للوم على فعل ماضٍ خاطئ", xp:18 },
      { id:"advmodal-t2-10", type:"listen_select", listenSentence:"It can't have been easy for them", options:["can't","mustn't","shouldn't","wouldn't"], correctAnswer:"can't", explanation:"الجملة: «ما كان ذلك سهلاً عليهم» — can't have للاستحالة في الماضي", xp:18 },
    ],
    // HIGH — exam-level, integrative, idiomatic, near-miss distractors
    t3: [
      { id:"advmodal-t3-1", type:"translate", arabic:"لا بد أنه قد أساء فهم التعليمات", options:["He must have misunderstood the instructions","He must misunderstood the instructions","He must have misunderstand the instructions","He may misunderstood the instructions"], correctAnswer:"He must have misunderstood the instructions", explanation:"must have + misunderstood — استنتاج قاطع عن سبب ماضٍ", xp:22 },
      { id:"advmodal-t3-2", type:"word_order", sentence:"You might as well tell the truth now", correctAnswer:"You might as well tell the truth now", explanation:"might as well — تعبير اصطلاحي: لا ضير من فعل الشيء طالما لا بديل", xp:23 },
      { id:"advmodal-t3-3", type:"translate", arabic:"كان من الممكن أن تسوء الأمور لولا تدخّله", options:["Things could have gone wrong but for his intervention","Things could go wrong but for his intervention","Things could have went wrong but for his intervention","Things must have gone wrong but for his intervention"], correctAnswer:"Things could have gone wrong but for his intervention", explanation:"could have gone + but for (لولا) لحدث افتراضي في الماضي", xp:24 },
      { id:"advmodal-t3-4", type:"listen_select", listenSentence:"Surely they cannot have overlooked such a detail", options:["cannot","must","might","would"], correctAnswer:"cannot", explanation:"الجملة: «بالتأكيد لم يكن بإمكانهم إغفال تفصيل كهذا» — cannot have للاستحالة", xp:23 },
      { id:"advmodal-t3-5", type:"word_order", sentence:"She would sooner resign than compromise her principles", correctAnswer:"She would sooner resign than compromise her principles", explanation:"would sooner ... than — تفضيل قوي يكافئ would rather", xp:24 },
      { id:"advmodal-t3-6", type:"translate", arabic:"ربما يكون قد بالغ في تقدير قدراته", options:["He may well have overestimated his abilities","He may good have overestimated his abilities","He may well have overestimate his abilities","He must well have overestimated his abilities"], correctAnswer:"He may well have overestimated his abilities", explanation:"may well + have + p.p — من المرجّح جداً", xp:24 },
      { id:"advmodal-t3-7", type:"word_order", sentence:"We had better address the issue promptly", correctAnswer:"We had better address the issue promptly", explanation:"had better + مصدر مجرد — نصيحة قوية فيها تحذير ضمني", xp:23 },
      { id:"advmodal-t3-8", type:"picture_match", word:"warning", pictureOptions:[{emoji:"⚠️",label:"warning"},{emoji:"✅",label:"approval"},{emoji:"❓",label:"question"},{emoji:"💡",label:"idea"}], correctAnswer:"warning", explanation:"had better ⚠️ يحمل معنى التحذير = warning", xp:22 },
      { id:"advmodal-t3-9", type:"translate", arabic:"ما كان ينبغي السماح بحدوث ذلك إطلاقاً", options:["That should never have been allowed to happen","That should never been allowed to happen","That should never have been allow to happen","That must never have been allowed to happen"], correctAnswer:"That should never have been allowed to happen", explanation:"should never have been + p.p — مبني للمجهول للوم على ماضٍ", xp:25 },
      { id:"advmodal-t3-10", type:"listen_select", listenSentence:"You ought to have consulted us beforehand", options:["ought","must","need","dare"], correctAnswer:"ought", explanation:"الجملة: «كان ينبغي أن تستشيرنا مسبقاً» — ought to have + p.p", xp:24 },
    ],
  },

  // ── Discourse Markers & Cohesion ──
  // Objective: addition markers (furthermore, in addition, moreover),
  // contrast (however, nevertheless, in contrast, despite), cause &
  // result (consequently, therefore, as a result), building cohesive text.
  "Discourse Markers & Cohesion": {
    // EASY — recognition of basic connectors
    t0: [
      { id:"discourse-t0-1", type:"word_order", sentence:"He is smart and he works hard", correctAnswer:"He is smart and he works hard", explanation:"and أبسط أداة لإضافة معلومة جديدة", xp:10 },
      { id:"discourse-t0-2", type:"translate", arabic:"هي متعبة، لكنها سعيدة", options:["She is tired, but she is happy","She is tired, so she is happy","She is tired, because she is happy","She is tired, and she is happy"], correctAnswer:"She is tired, but she is happy", explanation:"but أداة تناقض بسيطة", xp:10 },
      { id:"discourse-t0-3", type:"listen_select", listenSentence:"I study hard, therefore I pass", options:["therefore","however","because","although"], correctAnswer:"therefore", explanation:"الجملة: «أدرس بجدّ، لذلك أنجح» — therefore للنتيجة", xp:10 },
      { id:"discourse-t0-4", type:"picture_match", word:"addition", pictureOptions:[{emoji:"➕",label:"addition"},{emoji:"↔️",label:"contrast"},{emoji:"➡️",label:"result"},{emoji:"❓",label:"question"}], correctAnswer:"addition", explanation:"➕ = addition الإضافة مثل and/also/moreover", xp:10 },
      { id:"discourse-t0-5", type:"translate", arabic:"أحب القهوة وأيضاً الشاي", options:["I like coffee and also tea","I like coffee but also tea","I like coffee so also tea","I like coffee because also tea"], correctAnswer:"I like coffee and also tea", explanation:"also أداة إضافة شائعة", xp:11 },
      { id:"discourse-t0-6", type:"word_order", sentence:"It was late so we went home", correctAnswer:"It was late so we went home", explanation:"so تربط السبب بالنتيجة", xp:11 },
      { id:"discourse-t0-7", type:"translate", arabic:"درس كثيراً لذلك نجح", options:["He studied hard, so he passed","He studied hard, but he passed","He studied hard, or he passed","He studied hard, although he passed"], correctAnswer:"He studied hard, so he passed", explanation:"so للدلالة على النتيجة", xp:11 },
      { id:"discourse-t0-8", type:"listen_select", listenSentence:"I was tired but I finished", options:["but","and","so","because"], correctAnswer:"but", explanation:"الجملة: «كنت متعباً لكني أنهيت» — but للتناقض", xp:11 },
      { id:"discourse-t0-9", type:"word_order", sentence:"She was sick because of the cold weather", correctAnswer:"She was sick because of the cold weather", explanation:"because of + اسم للتعبير عن السبب", xp:11 },
      { id:"discourse-t0-10", type:"picture_match", word:"contrast", pictureOptions:[{emoji:"↔️",label:"contrast"},{emoji:"➕",label:"addition"},{emoji:"➡️",label:"result"},{emoji:"🔁",label:"repetition"}], correctAnswer:"contrast", explanation:"↔️ = contrast التناقض مثل but/however", xp:12 },
    ],
    // MEDIUM — more formal markers inside sentences
    t1: [
      { id:"discourse-t1-1", type:"translate", arabic:"الطعام لذيذ؛ علاوة على ذلك، السعر معقول", options:["The food is delicious; moreover, the price is reasonable","The food is delicious; however, the price is reasonable","The food is delicious; therefore, the price is reasonable","The food is delicious; otherwise, the price is reasonable"], correctAnswer:"The food is delicious; moreover, the price is reasonable", explanation:"moreover أداة إضافة رسمية = علاوة على ذلك", xp:13 },
      { id:"discourse-t1-2", type:"word_order", sentence:"However the plan was too expensive", correctAnswer:"However the plan was too expensive", explanation:"however للتناقض وتأتي عادة في بداية الجملة", xp:13 },
      { id:"discourse-t1-3", type:"translate", arabic:"كان الجو بارداً؛ لذلك بقينا في الداخل", options:["It was cold; therefore, we stayed inside","It was cold; moreover, we stayed inside","It was cold; however, we stayed inside","It was cold; for example, we stayed inside"], correctAnswer:"It was cold; therefore, we stayed inside", explanation:"therefore للنتيجة المنطقية", xp:14 },
      { id:"discourse-t1-4", type:"listen_select", listenSentence:"In addition we offered a discount", options:["addition","contrast","example","conclusion"], correctAnswer:"addition", explanation:"الجملة: «إضافةً إلى ذلك قدّمنا خصماً» — in addition للإضافة", xp:13 },
      { id:"discourse-t1-5", type:"word_order", sentence:"He was ill nevertheless he came to work", correctAnswer:"He was ill nevertheless he came to work", explanation:"nevertheless = ومع ذلك، تربط بين فكرتين متناقضتين", xp:14 },
      { id:"discourse-t1-6", type:"translate", arabic:"على الرغم من المطر، خرجنا", options:["Despite the rain, we went out","Although the rain, we went out","However the rain, we went out","Because the rain, we went out"], correctAnswer:"Despite the rain, we went out", explanation:"despite + اسم (لا جملة) للتعبير عن التناقض", xp:15 },
      { id:"discourse-t1-7", type:"word_order", sentence:"As a result the project was delayed", correctAnswer:"As a result the project was delayed", explanation:"as a result = نتيجةً لذلك", xp:14 },
      { id:"discourse-t1-8", type:"picture_match", word:"result", pictureOptions:[{emoji:"➡️",label:"result"},{emoji:"➕",label:"addition"},{emoji:"↔️",label:"contrast"},{emoji:"💡",label:"example"}], correctAnswer:"result", explanation:"➡️ = result النتيجة مثل therefore/as a result", xp:13 },
      { id:"discourse-t1-9", type:"translate", arabic:"إنه ذكي؛ من ناحية أخرى، فهو كسول", options:["He is clever; on the other hand, he is lazy","He is clever; in addition, he is lazy","He is clever; therefore, he is lazy","He is clever; for instance, he is lazy"], correctAnswer:"He is clever; on the other hand, he is lazy", explanation:"on the other hand لعرض الجانب المقابل", xp:15 },
      { id:"discourse-t1-10", type:"listen_select", listenSentence:"Consequently the prices increased", options:["Consequently","Furthermore","Meanwhile","Otherwise"], correctAnswer:"Consequently", explanation:"الجملة: «وبالتالي ارتفعت الأسعار» — consequently للنتيجة", xp:15 },
    ],
    // HARD — nuanced usage, distinctions, trap distractors
    t2: [
      { id:"discourse-t2-1", type:"translate", arabic:"كان متعباً؛ ومع ذلك، أنهى السباق", options:["He was exhausted; nevertheless, he finished the race","He was exhausted; furthermore, he finished the race","He was exhausted; therefore, he finished the race","He was exhausted; namely, he finished the race"], correctAnswer:"He was exhausted; nevertheless, he finished the race", explanation:"nevertheless للتناقض القوي رغم الظرف", xp:16 },
      { id:"discourse-t2-2", type:"word_order", sentence:"Despite his efforts the outcome was disappointing", correctAnswer:"Despite his efforts the outcome was disappointing", explanation:"Despite + اسم/عبارة اسمية للتناقض", xp:17 },
      { id:"discourse-t2-3", type:"translate", arabic:"لم يدرس؛ وبالتالي رسب في الامتحان", options:["He didn't study; consequently, he failed the exam","He didn't study; nonetheless, he failed the exam","He didn't study; likewise, he failed the exam","He didn't study; whereas, he failed the exam"], correctAnswer:"He didn't study; consequently, he failed the exam", explanation:"consequently للنتيجة المترتبة مباشرة", xp:17 },
      { id:"discourse-t2-4", type:"listen_select", listenSentence:"Whereas the north is rainy the south is dry", options:["Whereas","Whenever","Wherever","Whatever"], correctAnswer:"Whereas", explanation:"الجملة: «بينما الشمال ممطر، الجنوب جاف» — whereas للمقابلة", xp:17 },
      { id:"discourse-t2-5", type:"word_order", sentence:"In contrast the second method proved efficient", correctAnswer:"In contrast the second method proved efficient", explanation:"in contrast لإبراز فرق واضح بين أمرين", xp:16 },
      { id:"discourse-t2-6", type:"translate", arabic:"إنه باهظ الثمن؛ وفوق ذلك، يصعب استخدامه", options:["It is expensive; furthermore, it is hard to use","It is expensive; otherwise, it is hard to use","It is expensive; meanwhile, it is hard to use","It is expensive; instead, it is hard to use"], correctAnswer:"It is expensive; furthermore, it is hard to use", explanation:"furthermore لإضافة حجة مؤكِّدة أخرى", xp:17 },
      { id:"discourse-t2-7", type:"word_order", sentence:"Although it was risky they pursued the plan", correctAnswer:"Although it was risky they pursued the plan", explanation:"although + جملة كاملة للتناقض (تختلف عن despite + اسم)", xp:17 },
      { id:"discourse-t2-8", type:"picture_match", word:"link", pictureOptions:[{emoji:"🔗",label:"link"},{emoji:"✂️",label:"cut"},{emoji:"❓",label:"question"},{emoji:"⭐",label:"star"}], correctAnswer:"link", explanation:"🔗 = link أدوات الربط تربط الأفكار وتمنح النص تماسكاً", xp:16 },
      { id:"discourse-t2-9", type:"translate", arabic:"ينبغي مراجعة الخطة؛ وإلا فسنخسر العقد", options:["We should revise the plan; otherwise, we will lose the contract","We should revise the plan; therefore, we will lose the contract","We should revise the plan; moreover, we will lose the contract","We should revise the plan; namely, we will lose the contract"], correctAnswer:"We should revise the plan; otherwise, we will lose the contract", explanation:"otherwise = وإلا، تعرض نتيجة سلبية بديلة", xp:18 },
      { id:"discourse-t2-10", type:"listen_select", listenSentence:"Meanwhile the team prepared the report", options:["Meanwhile","Moreover","Therefore","However"], correctAnswer:"Meanwhile", explanation:"الجملة: «في الأثناء، أعدّ الفريق التقرير» — meanwhile للزمن المتزامن", xp:18 },
    ],
    // HIGH — sophisticated, formal, near-miss distractors
    t3: [
      { id:"discourse-t3-1", type:"translate", arabic:"تتطلب الحجة أدلة؛ وبالمثل، ينبغي أن تكون منطقية", options:["The argument requires evidence; likewise, it should be logical","The argument requires evidence; otherwise, it should be logical","The argument requires evidence; instead, it should be logical","The argument requires evidence; namely, it should be logical"], correctAnswer:"The argument requires evidence; likewise, it should be logical", explanation:"likewise = وبالمثل، لإضافة فكرة مماثلة", xp:22 },
      { id:"discourse-t3-2", type:"word_order", sentence:"Notwithstanding the objections the reform was adopted", correctAnswer:"Notwithstanding the objections the reform was adopted", explanation:"notwithstanding = رغم، أداة تناقض رسمية جداً", xp:24 },
      { id:"discourse-t3-3", type:"translate", arabic:"ثمة عيوب؛ ومع ذلك تظل الفوائد راجحة", options:["There are flaws; nonetheless, the benefits prevail","There are flaws; thereby, the benefits prevail","There are flaws; hence, the benefits prevail","There are flaws; whereby, the benefits prevail"], correctAnswer:"There are flaws; nonetheless, the benefits prevail", explanation:"nonetheless = ومع ذلك، أرقى من but في السياق الرسمي", xp:23 },
      { id:"discourse-t3-4", type:"listen_select", listenSentence:"Hence the committee revised its recommendations", options:["Hence","Hardly","Hereby","Hitherto"], correctAnswer:"Hence", explanation:"الجملة: «ومن ثمّ راجعت اللجنة توصياتها» — hence للنتيجة الرسمية", xp:23 },
      { id:"discourse-t3-5", type:"word_order", sentence:"By contrast the alternative approach yielded better results", correctAnswer:"By contrast the alternative approach yielded better results", explanation:"by contrast لإبراز التباين بين نهجين", xp:23 },
      { id:"discourse-t3-6", type:"translate", arabic:"لقد بذل قصارى جهده؛ وبالتالي يستحق الترقية", options:["He gave his utmost; thus, he deserves the promotion","He gave his utmost; albeit, he deserves the promotion","He gave his utmost; whereas, he deserves the promotion","He gave his utmost; lest, he deserves the promotion"], correctAnswer:"He gave his utmost; thus, he deserves the promotion", explanation:"thus = وبالتالي، أداة نتيجة رسمية", xp:24 },
      { id:"discourse-t3-7", type:"word_order", sentence:"Granted the idea is bold yet it remains untested", correctAnswer:"Granted the idea is bold yet it remains untested", explanation:"Granted ... yet — إقرار بنقطة ثم استدراك عليها", xp:24 },
      { id:"discourse-t3-8", type:"picture_match", word:"balance", pictureOptions:[{emoji:"⚖️",label:"balance"},{emoji:"🔗",label:"link"},{emoji:"➡️",label:"result"},{emoji:"❌",label:"contradiction"}], correctAnswer:"balance", explanation:"⚖️ = balance موازنة الحجج عبر on the one hand / on the other hand", xp:22 },
      { id:"discourse-t3-9", type:"translate", arabic:"تظل البيانات ناقصة؛ وعليه، فإن النتائج مبدئية", options:["The data remain incomplete; accordingly, the findings are tentative","The data remain incomplete; conversely, the findings are tentative","The data remain incomplete; alternatively, the findings are tentative","The data remain incomplete; incidentally, the findings are tentative"], correctAnswer:"The data remain incomplete; accordingly, the findings are tentative", explanation:"accordingly = وعليه، تربط النتيجة بالمقدمة المنطقية", xp:25 },
      { id:"discourse-t3-10", type:"listen_select", listenSentence:"Conversely the rural areas saw a decline", options:["Conversely","Concisely","Consciously","Constantly"], correctAnswer:"Conversely", explanation:"الجملة: «على العكس، شهدت المناطق الريفية تراجعاً» — conversely للتقابل", xp:24 },
    ],
  },

  // ── Formal Academic Writing ──
  // Objective: essay structure (intro, body, conclusion), building a strong
  // evidence-backed argument, formal style (no contractions, concision,
  // precision), citation, referencing and avoiding plagiarism.
  "Formal Academic Writing": {
    // EASY — recognition of basic concepts and terms
    t0: [
      { id:"acadwrite-t0-1", type:"word_order", sentence:"An essay has three main parts", correctAnswer:"An essay has three main parts", explanation:"المقال الأكاديمي: مقدمة وجسم وخاتمة", xp:10 },
      { id:"acadwrite-t0-2", type:"translate", arabic:"تقدّم المقدمة الموضوع الرئيسي", options:["The introduction presents the main topic","The conclusion presents the main topic","The body presents the main topic","The title presents the main topic"], correctAnswer:"The introduction presents the main topic", explanation:"المقدمة (introduction) تعرّف بالموضوع", xp:10 },
      { id:"acadwrite-t0-3", type:"listen_select", listenSentence:"Every paragraph needs a topic sentence", options:["topic","title","tone","term"], correctAnswer:"topic", explanation:"الجملة: «كل فقرة تحتاج جملة موضوعية» — topic sentence", xp:10 },
      { id:"acadwrite-t0-4", type:"picture_match", word:"essay", pictureOptions:[{emoji:"📄",label:"essay"},{emoji:"🎵",label:"song"},{emoji:"🖼️",label:"painting"},{emoji:"🎬",label:"film"}], correctAnswer:"essay", explanation:"📄 = essay المقال الأكاديمي", xp:10 },
      { id:"acadwrite-t0-5", type:"word_order", sentence:"The conclusion summarizes the main ideas", correctAnswer:"The conclusion summarizes the main ideas", explanation:"الخاتمة (conclusion) تلخّص الأفكار الرئيسية", xp:11 },
      { id:"acadwrite-t0-6", type:"translate", arabic:"يجب دعم الحجة بالأدلة", options:["The argument must be supported by evidence","The argument must be supported by emotion","The argument must be supported by opinion","The argument must be supported by colour"], correctAnswer:"The argument must be supported by evidence", explanation:"الحجة تحتاج أدلة (evidence) لا مشاعر", xp:11 },
      { id:"acadwrite-t0-7", type:"translate", arabic:"الكتابة الأكاديمية رسمية", options:["Academic writing is formal","Academic writing is informal","Academic writing is funny","Academic writing is spoken"], correctAnswer:"Academic writing is formal", explanation:"الأسلوب الأكاديمي رسمي (formal)", xp:11 },
      { id:"acadwrite-t0-8", type:"listen_select", listenSentence:"We must cite our sources", options:["cite","write","read","sing"], correctAnswer:"cite", explanation:"الجملة: «علينا توثيق مصادرنا» — cite = نوثّق/نستشهد", xp:11 },
      { id:"acadwrite-t0-9", type:"word_order", sentence:"The body develops the main argument", correctAnswer:"The body develops the main argument", explanation:"جسم المقال (body) يطوّر الحجة الرئيسية", xp:11 },
      { id:"acadwrite-t0-10", type:"picture_match", word:"book", pictureOptions:[{emoji:"📚",label:"book"},{emoji:"🎸",label:"guitar"},{emoji:"⚽",label:"ball"},{emoji:"🍕",label:"pizza"}], correctAnswer:"book", explanation:"📚 = book المصادر التي نقتبس ونوثّق منها", xp:12 },
    ],
    // MEDIUM — applying the rules, longer sentences
    t1: [
      { id:"acadwrite-t1-1", type:"translate", arabic:"ينبغي تجنّب الاختصارات في الكتابة الرسمية", options:["Contractions should be avoided in formal writing","Contractions should be used in formal writing","Contractions should be added in formal writing","Contractions should be repeated in formal writing"], correctAnswer:"Contractions should be avoided in formal writing", explanation:"نتجنّب الاختصارات (don't, can't) في الأسلوب الرسمي", xp:13 },
      { id:"acadwrite-t1-2", type:"word_order", sentence:"The thesis statement appears in the introduction", correctAnswer:"The thesis statement appears in the introduction", explanation:"thesis statement = الأطروحة، وتوضع في المقدمة", xp:13 },
      { id:"acadwrite-t1-3", type:"translate", arabic:"تربط الفقرة الأفكار بأدلة واضحة", options:["The paragraph links ideas with clear evidence","The paragraph links ideas with clear emotion","The paragraph links ideas with clear jokes","The paragraph links ideas with clear colours"], correctAnswer:"The paragraph links ideas with clear evidence", explanation:"الفقرة الجيدة تربط الأفكار بالأدلة", xp:14 },
      { id:"acadwrite-t1-4", type:"listen_select", listenSentence:"Always paraphrase to avoid plagiarism", options:["plagiarism","punctuation","paragraph","pronoun"], correctAnswer:"plagiarism", explanation:"الجملة: «أعد الصياغة دائماً لتجنّب الانتحال» — plagiarism", xp:14 },
      { id:"acadwrite-t1-5", type:"word_order", sentence:"We should write in the third person", correctAnswer:"We should write in the third person", explanation:"صيغة الغائب (third person) أكثر موضوعية ورسمية", xp:14 },
      { id:"acadwrite-t1-6", type:"translate", arabic:"يجب أن تكون اللغة دقيقة وموجزة", options:["The language should be precise and concise","The language should be vague and long","The language should be funny and casual","The language should be loud and slow"], correctAnswer:"The language should be precise and concise", explanation:"precise (دقيقة) و concise (موجزة) سمتا الكتابة الأكاديمية", xp:15 },
      { id:"acadwrite-t1-7", type:"word_order", sentence:"Each claim must be backed by evidence", correctAnswer:"Each claim must be backed by evidence", explanation:"كل ادعاء (claim) يجب أن تسنده أدلة", xp:14 },
      { id:"acadwrite-t1-8", type:"picture_match", word:"quote", pictureOptions:[{emoji:"💬",label:"quote"},{emoji:"🎤",label:"sing"},{emoji:"🏃",label:"run"},{emoji:"🍳",label:"cook"}], correctAnswer:"quote", explanation:"💬 = quote الاقتباس المباشر يوضع بين علامتي تنصيص", xp:13 },
      { id:"acadwrite-t1-9", type:"translate", arabic:"تقدّم الخاتمة توصية نهائية", options:["The conclusion offers a final recommendation","The introduction offers a final recommendation","The body offers a final recommendation","The title offers a final recommendation"], correctAnswer:"The conclusion offers a final recommendation", explanation:"الخاتمة قد تقدّم توصية أو استنتاجاً نهائياً", xp:15 },
      { id:"acadwrite-t1-10", type:"listen_select", listenSentence:"A reference list appears at the end", options:["reference","reverence","reflection","refreshment"], correctAnswer:"reference", explanation:"الجملة: «تأتي قائمة المراجع في النهاية» — reference list", xp:15 },
    ],
    // HARD — nuanced conventions, trap distractors
    t2: [
      { id:"acadwrite-t2-1", type:"translate", arabic:"ينبغي توثيق كل اقتباس بدقة", options:["Every quotation should be referenced accurately","Every quotation should be ignored accurately","Every quotation should be invented accurately","Every quotation should be hidden accurately"], correctAnswer:"Every quotation should be referenced accurately", explanation:"كل اقتباس يجب توثيقه (referenced) بدقة", xp:16 },
      { id:"acadwrite-t2-2", type:"word_order", sentence:"A coherent essay maintains a logical flow", correctAnswer:"A coherent essay maintains a logical flow", explanation:"المقال المتماسك (coherent) يحافظ على تدفّق منطقي", xp:17 },
      { id:"acadwrite-t2-3", type:"translate", arabic:"ينبغي صياغة الحجة بموضوعية لا بانفعال", options:["The argument should be framed objectively, not emotionally","The argument should be framed emotionally, not objectively","The argument should be framed loudly, not objectively","The argument should be framed quickly, not objectively"], correctAnswer:"The argument should be framed objectively, not emotionally", explanation:"objectively (بموضوعية) سمة الكتابة الأكاديمية", xp:18 },
      { id:"acadwrite-t2-4", type:"listen_select", listenSentence:"Hedging language softens academic claims", options:["Hedging","Heading","Healing","Hearing"], correctAnswer:"Hedging", explanation:"الجملة: «لغة التحوّط تلطّف الادعاءات» — hedging (may, tend to, suggest)", xp:17 },
      { id:"acadwrite-t2-5", type:"word_order", sentence:"Strong evidence strengthens a persuasive argument", correctAnswer:"Strong evidence strengthens a persuasive argument", explanation:"الأدلة القوية تعزّز الحجة المقنعة", xp:16 },
      { id:"acadwrite-t2-6", type:"translate", arabic:"يجب أن تتدفّق الفقرات بسلاسة من فكرة إلى أخرى", options:["Paragraphs should flow smoothly from one idea to the next","Paragraphs should jump randomly from one idea to the next","Paragraphs should repeat slowly from one idea to the next","Paragraphs should stop suddenly from one idea to the next"], correctAnswer:"Paragraphs should flow smoothly from one idea to the next", explanation:"التماسك يتطلب انتقالاً سلساً (flow) بين الأفكار", xp:17 },
      { id:"acadwrite-t2-7", type:"word_order", sentence:"The writer must acknowledge opposing viewpoints", correctAnswer:"The writer must acknowledge opposing viewpoints", explanation:"الإقرار بوجهات النظر المخالفة يقوّي الحجة", xp:17 },
      { id:"acadwrite-t2-8", type:"picture_match", word:"evidence", pictureOptions:[{emoji:"🔍",label:"evidence"},{emoji:"🎨",label:"art"},{emoji:"🎲",label:"chance"},{emoji:"😂",label:"humour"}], correctAnswer:"evidence", explanation:"🔍 = evidence الأدلة التي تدعم الحجة الأكاديمية", xp:16 },
      { id:"acadwrite-t2-9", type:"translate", arabic:"إعادة الصياغة دون إسناد تُعدّ انتحالاً", options:["Paraphrasing without attribution counts as plagiarism","Paraphrasing without attribution counts as creativity","Paraphrasing without attribution counts as evidence","Paraphrasing without attribution counts as citation"], correctAnswer:"Paraphrasing without attribution counts as plagiarism", explanation:"إعادة الصياغة دون إسناد (attribution) انتحال", xp:18 },
      { id:"acadwrite-t2-10", type:"listen_select", listenSentence:"A counterargument anticipates the reader objections", options:["counterargument","counterfeit","countryside","counting"], correctAnswer:"counterargument", explanation:"الجملة: «الحجة المضادة تستبق اعتراضات القارئ» — counterargument", xp:18 },
    ],
    // HIGH — sophisticated academic conventions, near-miss distractors
    t3: [
      { id:"acadwrite-t3-1", type:"translate", arabic:"ينبغي أن تستند الأطروحة إلى أدلة تجريبية لا إلى تخمين", options:["The thesis should rest on empirical evidence rather than conjecture","The thesis should rest on empirical evidence rather than research","The thesis should rest on emotional evidence rather than conjecture","The thesis should rest on empirical evidence rather than facts"], correctAnswer:"The thesis should rest on empirical evidence rather than conjecture", explanation:"empirical evidence (أدلة تجريبية) مقابل conjecture (تخمين)", xp:23 },
      { id:"acadwrite-t3-2", type:"word_order", sentence:"A nuanced argument concedes the limitations of its evidence", correctAnswer:"A nuanced argument concedes the limitations of its evidence", explanation:"الحجة المتزنة تقرّ بحدود أدلتها (concede limitations)", xp:24 },
      { id:"acadwrite-t3-3", type:"translate", arabic:"ينبغي توثيق المصادر وفق نمط استشهاد متسق", options:["Sources should be documented in a consistent citation style","Sources should be documented in a careless citation style","Sources should be documented in a random citation style","Sources should be documented in a spoken citation style"], correctAnswer:"Sources should be documented in a consistent citation style", explanation:"التزام نمط استشهاد متسق (APA/MLA) ضرورة أكاديمية", xp:23 },
      { id:"acadwrite-t3-4", type:"listen_select", listenSentence:"Plagiarism undermines academic integrity", options:["integrity","intensity","intimacy","intricacy"], correctAnswer:"integrity", explanation:"الجملة: «الانتحال يقوّض النزاهة الأكاديمية» — integrity", xp:23 },
      { id:"acadwrite-t3-5", type:"word_order", sentence:"The conclusion should synthesize rather than merely repeat", correctAnswer:"The conclusion should synthesize rather than merely repeat", explanation:"الخاتمة تركّب الأفكار (synthesize) لا تكرّرها فحسب", xp:24 },
      { id:"acadwrite-t3-6", type:"translate", arabic:"تتسم الكتابة الرصينة بالإيجاز والدقة والحياد", options:["Rigorous writing is marked by concision, precision and impartiality","Rigorous writing is marked by repetition, vagueness and bias","Rigorous writing is marked by concision, vagueness and bias","Rigorous writing is marked by humour, precision and impartiality"], correctAnswer:"Rigorous writing is marked by concision, precision and impartiality", explanation:"concision (إيجاز) precision (دقة) impartiality (حياد)", xp:25 },
      { id:"acadwrite-t3-7", type:"word_order", sentence:"Empirical data must substantiate every sweeping claim", correctAnswer:"Empirical data must substantiate every sweeping claim", explanation:"البيانات التجريبية تثبت (substantiate) الادعاءات الواسعة", xp:24 },
      { id:"acadwrite-t3-8", type:"picture_match", word:"structure", pictureOptions:[{emoji:"🏛️",label:"structure"},{emoji:"🎲",label:"chance"},{emoji:"🎭",label:"drama"},{emoji:"🌧️",label:"rain"}], correctAnswer:"structure", explanation:"🏛️ = structure هيكل المقال: مقدمة وجسم وخاتمة", xp:22 },
      { id:"acadwrite-t3-9", type:"translate", arabic:"ينبغي أن يظل صوت الكاتب موضوعياً ومتجرداً من التحيّز", options:["The writer's voice should remain objective and free of bias","The writer's voice should remain subjective and full of bias","The writer's voice should remain casual and free of bias","The writer's voice should remain objective and full of slang"], correctAnswer:"The writer's voice should remain objective and free of bias", explanation:"الصوت الأكاديمي موضوعي (objective) ومتحرّر من التحيّز (bias)", xp:25 },
      { id:"acadwrite-t3-10", type:"listen_select", listenSentence:"Accurate attribution preserves scholarly credibility", options:["attribution","distribution","contribution","retribution"], correctAnswer:"attribution", explanation:"الجملة: «الإسناد الدقيق يحفظ المصداقية العلمية» — attribution", xp:24 },
    ],
  },
};
